name: Scheduled Reddit Stocks Script (uv)

on:
  schedule:
    - cron: '0 0 * * 1,3'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Automatically manages caching for you
          enable-cache: true
          # You can specify the python version directly here
          python-version: '3.13'

      - name: Run Script with uv
        run: |
          DAY=$(date +%u)

          if [ "$DAY" -eq 1 ]; then
            SUBREDDIT="ValueInvesting"
          elif [ "$DAY" -eq 3 ]; then
            SUBREDDIT="stocks"
          fi

          # 'uv run' handles environment creation and dependency 
          # installation automatically if you have a pyproject.toml
          uv run python reddit_stocks.py "$SUBREDDIT"
